#### `10.3-Data Manipulation and Analysis with Pandas and Numpy`

* Data Manipulation and analysis are key tasks in any `data science` or `data analysis` project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. Now we cover various data manipulation and analysis techniques using `Pandas`

In [2]:
import pandas as pd

In [12]:
df =pd.read_csv('Smartphones.csv')

In [13]:
## fetching first 5 rows
df.head()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.1,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.1,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.5,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.1,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.1,60,2,ios,12.0,12.0,0,2532,1170

In [14]:
df.tail(5)

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.3,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.3,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.3,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.2,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.0,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

In [6]:
## description of data
df.describe()

,ID,Reason for Absence,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,17.951429,19.411429,222.347143,29.892857,36.417143,271.801774,26.737143,1.282857,1.021429,0.687143,6.761429
std,11.028144,8.356292,66.312960,14.804446,6.379083,40.021804,4.254701,0.668090,1.112215,1.166095,12.670082
min,1.000000,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,1.000000,0.000000,0.000000,0.000000
25%,9.000000,13.000000,179.000000,16.000000,31.000000,241.476000,24.000000,1.000000,0.000000,0.000000,2.000000
50%,18.000000,23.000000,225.000000,26.000000,37.000000,264.249000,25.000000,1.000000,1.000000,0.000000,3.000000
75%,28.000000,27.000000,260.000000,50.000000,40.000000,294.217000,31.000000,1.000000,2.000000,1.000000,8.000000
max,36.000000,28.000000,388.000000,52.000000,58.000000,378.884000,38.000000,4.000000,4.000000,8.000000,120.000000

In [15]:
## to check the data type
df.dtypes

brand_name                    object
model                         object
price                          int64
avg_rating                   float64
5G_or_not                      int64
processor_brand               object
num_cores                    float64
processor_speed              float64
battery_capacity             float64
fast_charging_available        int64
fast_charging                float64
ram_capacity                   int64
internal_memory                int64
screen_size                  float64
refresh_rate                   int64
num_rear_cameras               int64
os                            object
primary_camera_rear          float64
primary_camera_front         float64
extended_memory_available      int64
resolution_height              int64
resolution_width               int64
dtype: object

1- `Handling Missing Values`

In [16]:
df.isnull().sum()

brand_name                     0
model                          0
price                          0
avg_rating                   101
5G_or_not                      0
processor_brand               20
num_cores                      6
processor_speed               42
battery_capacity              11
fast_charging_available        0
fast_charging                211
ram_capacity                   0
internal_memory                0
screen_size                    0
refresh_rate                   0
num_rear_cameras               0
os                            14
primary_camera_rear            0
primary_camera_front           5
extended_memory_available      0
resolution_height              0
resolution_width               0
dtype: int64

* To check the missing value `with respect to every record` we do

In [17]:
df.isnull().any(axis=1)  # It return "True " if any record has a missing value and "False" if record has no missing value

0       True
1       True
2      False
3       True
4       True
       ...
975    False
976    False
977    False
978    False
979    False
Length: 980, dtype: bool

In [18]:
df.isnull().any()  # by default the axis=0, it check for each column

brand_name                   False
model                        False
price                        False
avg_rating                    True
5G_or_not                    False
processor_brand               True
num_cores                     True
processor_speed               True
battery_capacity              True
fast_charging_available      False
fast_charging                 True
ram_capacity                 False
internal_memory              False
screen_size                  False
refresh_rate                 False
num_rear_cameras             False
os                            True
primary_camera_rear          False
primary_camera_front          True
extended_memory_available    False
resolution_height            False
resolution_width             False
dtype: bool

i-` fill all the missing with 0`

In [ ]:
## to fill all the missing with 0
df_filled = df.fillna(0)

ii-` fill all the missing with mean of the columns`

In [22]:
df['avg_rating_fillNA_mean'] = df['avg_rating'].fillna(df['avg_rating'].mean())

In [24]:
df.head(3)

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width,avg_rating_fillNA_mean
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,6.1,60,2,ios,12.0,12.0,0,1792,828,7.3
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,6.1,60,2,ios,12.0,12.0,0,1792,828,7.5
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,6.5,60,3,ios,12.0,12.0,0,2688,1242,7.7

iii-`Changing type of column`

In [25]:
df.dtypes

brand_name                    object
model                         object
price                          int64
avg_rating                   float64
5G_or_not                      int64
processor_brand               object
num_cores                    float64
processor_speed              float64
battery_capacity             float64
fast_charging_available        int64
fast_charging                float64
ram_capacity                   int64
internal_memory                int64
screen_size                  float64
refresh_rate                   int64
num_rear_cameras               int64
os                            object
primary_camera_rear          float64
primary_camera_front         float64
extended_memory_available      int64
resolution_height              int64
resolution_width               int64
avg_rating_fillNA_mean       float64
dtype: object

In [26]:
### Renaming column
df = df.rename(columns={'model':"Phone_Model"})

In [27]:
df.head()

,brand_name,Phone_Model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width,avg_rating_fillNA_mean
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,6.1,60,2,ios,12.0,12.0,0,1792,828,7.3
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,6.1,60,2,ios,12.0,12.0,0,1792,828,7.5
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,6.5,60,3,ios,12.0,12.0,0,2688,1242,7.7
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,6.1,60,2,ios,12.0,12.0,0,2532,1170,7.4
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,6.1,60,2,ios,12.0,12.0,0,2532,1170,7.5

In [31]:
## Changing the data type 

df['Value_new'] = df['avg_rating'].astype('float16')

In [32]:
df.dtypes

brand_name                    object
Phone_Model                   object
price                          int64
avg_rating                   float64
5G_or_not                      int64
processor_brand               object
num_cores                    float64
processor_speed              float64
battery_capacity             float64
fast_charging_available        int64
fast_charging                float64
ram_capacity                   int64
internal_memory                int64
screen_size                  float64
refresh_rate                   int64
num_rear_cameras               int64
os                            object
primary_camera_rear          float64
primary_camera_front         float64
extended_memory_available      int64
resolution_height              int64
resolution_width               int64
avg_rating_fillNA_mean       float64
Value_new                    float16
dtype: object

In [33]:
df['New_value'] = df['Value_new'].apply(lambda x:x*2)

In [34]:
df.head(3)

d:\University\DataScience\Specialization\venv\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
d:\University\DataScience\Specialization\venv\Lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,brand_name,Phone_Model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width,avg_rating_fillNA_mean,Value_new,New_value
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,2,ios,12.0,12.0,0,1792,828,7.3,7.300781,14.601562
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,2,ios,12.0,12.0,0,1792,828,7.5,7.500000,15.000000
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,3,ios,12.0,12.0,0,2688,1242,7.7,7.699219,15.398438

3- `Data Aggregating and Grouping`

* Based on the `os (operating system)` i want to find the `average rating of each brand`

In [41]:
## if we want to aggregate
grouped_avg_rating = df.groupby('os')['avg_rating'].mean()

print(grouped_avg_rating)

os
android    7.822344
ios        7.679545
other      8.042857
Name: avg_rating, dtype: float64

3.1 - `If I have to group by based on two categories`

In [48]:
df.groupby(['brand_name','os'])['avg_rating'].mean().head(5)

brand_name  os
apple       ios        7.679545
asus        android    8.700000
blackview   android    6.700000
blu         android    8.500000
cola        android    7.400000
Name: avg_rating, dtype: float64

In [52]:
df.groupby(['brand_name','os'])['price'].sum().head(10)

brand_name  os
apple       ios        4414460
asus        android     414976
blackview   android       8990
blu         android      14990
cola        android      14999
doogee      android      60998
duoqin      android       9990
gionee      android      14498
            other         6190
google      android     620656
Name: price, dtype: int64

4- `Multiple Aggregate functions`

In [58]:
df.groupby(['processor_brand','os'])['price'].agg(['mean','sum','max','min','count'])

                                 mean       sum     max    min  count
processor_brand os
bionic          ios      96921.555556   4361470  182999  29990     45
dimensity       android  25068.959770   4361999   72999   9999    174
exynos          android  37841.520000   1892076  105999  10499     50
fusion          ios      52990.000000     52990   52990  52990      1
google          android  55505.333333    499548   81999  29999      9
helio           android  12405.930000   2481186   29990   3499    200
kirin           android  82729.750000    330919  214990  10949      4
                other    84990.000000    169980   99990  69990      2
mediatek        android   4999.000000      4999    4999   4999      1
sc9863a         android   7124.000000     14248    7749   6499      2
snapdragon      android  37960.327456  15070250  650000   3890    397
                other    74849.714286    523948  239999  22990      7
spreadtrum      android   5568.750000     22275    6999   3999      4
tiger           android   9221.652174    212098   13999   5299     23
                other     6190.000000      6190    6190   6190      1
unisoc          android   8115.153846    210994   13499   5249     26

5-`Merging and Joining DataFrame`

In [59]:
## Sample data frame
df1 = pd.DataFrame({'Key':['A','B','C'],'Value':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'],'Value':[4,5,6]})

In [60]:
df1

  Key  Value
0   A      1
1   B      2
2   C      3

In [61]:
df2

  Key  Value
0   A      4
1   B      5
2   D      6

4.1 - Merging dataframe on basis of `key column`

* how = `inner` : mean that only matching column need to be kept

![alt text](images.png)

![alt text](join-types-merge-names.jpg)

In [62]:
pd.merge(df1,df2,on = 'Key',how='inner')

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

* how =`Outer or Full`

In [65]:
pd.merge(df1,df2,on = 'Key',how='outer')

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

* `left` dataframe is taken overall and from right only the matching will be kept

In [ ]:
pd.merge(df1,df2,on = 'Key',how='left')

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

* `right` right is taken overall and left only matching will be keep

In [67]:
pd.merge(df1,df2,on = 'Key',how='right')

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6

### `Conclusion`
* We have discussed various data manipulation techniques using pandas, including handling missing values, renaming columns, changing data types, applying functions, aggregation, grouping, and merging DataFrames. These foundational skills are essential for effective data analysis. More advanced topics will be explored in upcoming sessions.

### `Key Takeaways`
- Pandas is a powerful library for data manipulation and exploratory data analysis in Python.
- Handling missing values, renaming columns, and changing data types are essential data cleaning steps.
- Aggregation and grouping operations allow for insightful analysis based on categorical variables.
- Merging and joining DataFrames enable combining datasets for comprehensive analysis.