### `Reading Data`

In [1]:
import pandas as pd
from io import StringIO

* If you have a `key- value` pairs then you can converted that into a `dataframe`

In [9]:
data = '{"employee_name":"shoaib","email":"shoaib@gmail.com","job_profile":[{"title_1":"team_lead","title_2":"Sr.Developer","title_3":"AI Engineer"}]}'

df = pd.read_json(StringIO(data))
df

,employee_name,email,job_profile
0,shoaib,shoaib@gmail.com,"{'title_1': 'team_lead', 'title_2': 'Sr.Develo..."

* If I want to convert the `dataframe` back into a `json`

In [11]:
df.to_json()

'{"employee_name":{"0":"shoaib"},"email":{"0":"shoaib@gmail.com"},"job_profile":{"0":{"title_1":"team_lead","title_2":"Sr.Developer","title_3":"AI Engineer"}}}'

* but above you can see the conversion into json give some issue because it give some else key

In [ ]:
## to convert into json based on records we pass a argument to "orients=records" by default it is orient =index

df.to_json(orient='records')  # now it give us correct anser

'[{"employee_name":"shoaib","email":"shoaib@gmail.com","job_profile":{"title_1":"team_lead","title_2":"Sr.Developer","title_3":"AI Engineer"}}]'

2-`Reading data from `

In [15]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data'
df_url = pd.read_csv(url,header=None)

In [16]:
df_url.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [22]:
# we can convert this dataframe into csv file
df_url.to_csv('wine.csv')

3-`Reading Data From HTML file`

In [ ]:
# Installing dependencies 
# !pip install lxml html5lib beautifulsoup4

Collecting lxml
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: six>=1.9 in d:\university\datascience\specialization\venv\lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\university\datascience\specialization\venv\lib\site-packages (from beautifulsoup4) (4.15.0)
Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 356.7 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 356.7 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 356.7 kB/s eta 0:00:10
   ------- -------------------------------- 0.8/4.0 MB 364.6 kB/s eta 0:00:09
   ------- -------------------------------- 0.8/4.0 MB 364.6 kB/s eta 0:00:09
   ------- -------------------------------- 0.8/4.0 MB 364.6 kB/s eta 0:00:09
   ------- -------------------------------- 0.8/4.0 MB 364.6 kB/s eta 0:00:09
   ---------- ----------------------------- 1.0/4.0 MB 370.1 kB/s eta 0:00:09
   ---------- ----------------------------- 1.0/4.0 MB 370.1 kB/s eta 0:00:09
   ---------- ----------------------------- 1.0/4.0 MB 370.1 kB/s eta 0:00:09
   ------------- -------------------------- 1.3/4.0 MB 370.8 kB/s eta 0:00:08
   ------------- -------------------------- 1.3/4.0 MB 370.8 kB/s eta 0:00:08
   ------------- -------------------------- 1.3/4.0 MB 370.8 kB/s eta 0:00:08
   --------------- ------------------------ 1.6/4.0 MB 366.3 kB/s eta 0:00:07
   --------------- ------------------------ 1.6/4.0 MB 366.3 kB/s eta 0:00:07
   --------------- ------------------------ 1.6/4.0 MB 366.3 kB/s eta 0:00:07
   --------------- ------------------------ 1.6/4.0 MB 366.3 kB/s eta 0:00:07
   ------------------ --------------------- 1.8/4.0 MB 366.0 kB/s eta 0:00:06
   ------------------ --------------------- 1.8/4.0 MB 366.0 kB/s eta 0:00:06
   ------------------ --------------------- 1.8/4.0 MB 366.0 kB/s eta 0:00:06
   -------------------- ------------------- 2.1/4.0 MB 365.8 kB/s eta 0:00:06
   -------------------- ------------------- 2.1/4.0 MB 365.8 kB/s eta 0:00:06
   -------------------- ------------------- 2.1/4.0 MB 365.8 kB/s eta 0:00:06
   -------------------- ------------------- 2.1/4.0 MB 365.8 kB/s eta 0:00:06
   ----------------------- ---------------- 2.4/4.0 MB 365.7 kB/s eta 0:00:05
   ----------------------- ---------------- 2.4/4.0 MB 365.7 kB/s eta 0:00:05
   ----------------------- ---------------- 2.4/4.0 MB 365.7 kB/s eta 0:00:05
   -------------------------- ------------- 2.6/4.0 MB 366.5 kB/s eta 0:00:04
   -------------------------- ------------- 2.6/4.0 MB 366.5 kB/s eta 0:00:04
   -------------------------- ------------- 2.6/4.0 MB 366.5 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 366.3 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 366.3 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 366.3 kB/s eta 0:00:04
   ---------------------------- ----------- 2.9/4.0 MB 366.3 kB/s eta 0:00:04
   ------------------------------- -------- 3.1/4.0 MB 366.2 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 366.2 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 366.2 kB/s eta 0:00:03
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 364.7 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 282.2 kB/s eta 0:00:02
   ---------------------------------------  3.9/4.0 MB 208.8 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 208.8 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 208.8 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 208.8 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 208.8 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 208.8 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 199.7 kB/s  0:00:18
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.1-py3-none-any.whl (36 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, soupsieve, lxml, html5lib, beautifulsoup4

   -------- ------------------------------- 1/5 [soupsieve]
   -------- ------------------------------- 1/5 [soupsieve]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ---------------- ----------------------- 2/5 [lxml]
   ------------------------ --------------- 3/5 [html5lib]
   ------------------------ --------------- 3/5 [html5lib]
   ------------------------ --------------- 3/5 [html5lib]
   ------------------------ --------------- 3/5 [html5lib]
   ------------------------ --------------- 3/5 [html5lib]
   -------------------------------- ------- 4/5 [beautifulsoup4]
   -------------------------------- ------- 4/5 [beautifulsoup4]
   -------------------------------- ------- 4/5 [beautifulsoup4]
   ---------------------------------------- 5/5 [beautifulsoup4]

Successfully installed beautifulsoup4-4.14.3 html5lib-1.1 lxml-6.0.2 soupsieve-2.8.1 webencodings-0.5.1

In [25]:
url_html = 'https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/'
df_html =pd.read_html(url_html)   # it give us a list of tables
df_html

[                                            Bank Name                City  \
 0                        The Santa Anna National Bank          Santa Anna
 1                                Pulaski Savings Bank             Chicago
 2                  The First National Bank of Lindsay             Lindsay
 3               Republic First Bank dba Republic Bank        Philadelphia
 4                                       Citizens Bank            Sac City
 5                            Heartland Tri-State Bank             Elkhart
 6                                 First Republic Bank       San Francisco
 7                                      Signature Bank            New York
 8                                 Silicon Valley Bank         Santa Clara
 9                                   Almena State Bank              Almena
 10                         First City Bank of Florida   Fort Walton Beach
 11                               The First State Bank       Barboursville
 12                                 Ericson State Bank             Ericson
 13                   City National Bank of New Jersey              Newark
 14                                      Resolute Bank              Maumee
 15                              Louisa Community Bank              Louisa
 16                               The Enloe State Bank              Cooper
 17                Washington Federal Bank for Savings             Chicago
 18    The Farmers and Merchants State Bank of Argonia             Argonia
 19                                Fayette County Bank          Saint Elmo
 20  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 21                                     First NBC Bank         New Orleans
 22                                      Proficio Bank  Cottonwood Heights
 23                      Seaway Bank and Trust Company             Chicago
 24                             Harvest Community Bank          Pennsville

             State   Cert                Acquiring Institution  \
 0           Texas   5520            Coleman County State Bank
 1        Illinois  28611                      Millennium Bank
 2        Oklahoma   4134               First Bank & Trust Co.
 3    Pennsylvania  27332    Fulton Bank, National Association
 4            Iowa   8758            Iowa Trust & Savings Bank
 5          Kansas  25851               Dream First Bank, N.A.
 6      California  59017            JPMorgan Chase Bank, N.A.
 7        New York  57053                  Flagstar Bank, N.A.
 8      California  24735  First Citizens Bank & Trust Company
 9          Kansas  15426                          Equity Bank
 10        Florida  16748            United Fidelity Bank, fsb
 11  West Virginia  14361                       MVB Bank, Inc.
 12       Nebraska  18265           Farmers and Merchants Bank
 13     New Jersey  21111                      Industrial Bank
 14           Ohio  58317                   Buckeye State Bank
 15       Kentucky  58112    Kentucky Farmers Bank Corporation
 16          Texas  10716                   Legend Bank, N. A.
 17       Illinois  30570                   Royal Savings Bank
 18         Kansas  17719                          Conway Bank
 19       Illinois   1802            United Fidelity Bank, fsb
 20      Wisconsin  30003  First-Citizens Bank & Trust Company
 21      Louisiana  58302                         Whitney Bank
 22           Utah  35495                    Cache Valley Bank
 23       Illinois  19328                  State Bank of Texas
 24     New Jersey  34951  First-Citizens Bank & Trust Company

          Closing Date  Fund  Sort ascending
 0       June 27, 2025                 10549
 1    January 17, 2025                 10548
 2    October 18, 2024                 10547
 3      April 26, 2024                 10546
 4    November 3, 2023                 10545
 5       July 28, 2023                 10544
 6         May 1, 2023                 10543
 7      March 12, 2023                 10540
 8      March 10, 2023                 10539
 9    October 23, 2020                 10538
 10   October 16, 2020                 10537
 11      April 3, 2020                 10536
 12  February 14, 2020                 10535
 13   November 1, 2019                 10534
 14   October 25, 2019                 10533
 15   October 25, 2019                 10532
 16       May 31, 2019                 10531
 17  December 15, 2017                 10530
 18   October 13, 2017                 10529
 19       May 26, 2017                 10528
 20        May 5, 2017                 10527
 21     April 28, 2017                 10526
 22      March 3, 2017                 10525
 23   January 27, 2017                 10524
 24   January 13, 2017                 10523  ]

In [30]:
df_html = df_html[0]

In [31]:
df_html.head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545

In [34]:
u = 'https://www.w3schools.com/html/html_tables.asp'
w3_school_df = pd.read_html(u)[0]
w3_school_df

                        Company           Contact  Country
0           Alfreds Futterkiste      Maria Anders  Germany
1    Centro comercial Moctezuma   Francisco Chang   Mexico
2                  Ernst Handel     Roland Mendel  Austria
3                Island Trading     Helen Bennett       UK
4  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
5  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

4-`Read Excel data`

In [ ]:
# pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [42]:
df_excel  = pd.read_excel("uncleaned bike sales data.xlsx")

In [43]:
df_excel.head()

,Sales_Order #,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product_Description,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,261695,2021-12-01,1.0,December,2021,39,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",4.0,1252,2295,4172,5008,9180
1,261695,2021-12-01,1.0,December,2021,44,Adults (35-64),M,United Kingdom,England,Bikes,Mountain Bikes,"Mountain-200 Silver, 42",1.0,1266,2320,1054,1266,2320
2,261697,2021-12-02,2.0,December,2021,37,Adults (35-64),M,United States,California,Bikes,Mountain Bikes,"Mountain-400-W Silver, 46",2.0,420,769,698,840,1538
3,261698,2021-12-02,2.0,December,2021,31,Young Adults (25-34),F,Australia,New South Wales,Bikes,Mountain Bikes,"Mountain-400-W Silver, 42",1.0,420,769,349,420,769
4,261699,2021-12-03,3.0,December,2021,37,Adults (35-64),F,United States,California,Bikes,Mountain Bikes,"Mountain-200 Black, 46",2.0,0,2295,2086,0,4590