### **Applying Naive Bayes on Strokes Data**

In [14]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [24]:
train_df = pd.read_csv('../05. SVM\stroke_train_data.csv')
test_df = pd.read_csv('../05. SVM\stroke_test_data.csv')

In [20]:
# df.drop(columns=['Unnamed: 0','index'],axis=1,inplace=True)

In [25]:
train_df.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0.0,0.209397,0,0,1,1,-0.821221,0.551632,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1,0.0,-0.629845,0,0,0,1,-0.485884,-0.982537,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2,0.0,-0.364822,0,0,1,0,0.302317,-0.763370,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
3,1.0,-0.232310,0,0,1,0,0.062342,0.500063,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
4,1.0,-1.292405,0,0,0,1,-0.527297,0.358249,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0

In [26]:
test_df.head()

,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,work_type_Govt_job,work_type_Never_worked,work_type_Private,work_type_Self-employed,work_type_children,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,stroke
0,0.0,-0.674016,1,0,1,0,-0.497748,0.977074,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1,0.0,-1.778282,0,0,0,1,-0.281950,-1.201704,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0
2,0.0,0.430250,0,0,1,0,-0.928896,0.280896,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,1.0,-0.364822,0,0,1,0,-0.820997,1.802173,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
4,0.0,0.651103,0,0,1,0,-0.259564,0.035945,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0

In [27]:
train_df.isnull().sum()

gender                            0
age                               0
hypertension                      0
heart_disease                     0
ever_married                      0
Residence_type                    0
avg_glucose_level                 0
bmi                               0
work_type_Govt_job                0
work_type_Never_worked            0
work_type_Private                 0
work_type_Self-employed           0
work_type_children                0
smoking_status_Unknown            0
smoking_status_formerly smoked    0
smoking_status_never smoked       0
smoking_status_smokes             0
stroke                            0
dtype: int64

In [ ]:
## training data split
X_train,y_train = train_df.drop('stroke',axis=1),train_df['stroke']

In [30]:
## test data split
X_test,y_test = test_df.drop('stroke',axis=1),test_df['stroke']

## `Applying Gussain Naive Bayes`

In [28]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB

In [31]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.363013698630137
[[322 650]
 [  1  49]]
              precision    recall  f1-score   support

           0       1.00      0.33      0.50       972
           1       0.07      0.98      0.13        50

    accuracy                           0.36      1022
   macro avg       0.53      0.66      0.31      1022
weighted avg       0.95      0.36      0.48      1022

In [33]:
bnb = BernoulliNB()
bnb.fit(X_train,y_train)
y_pred = bnb.predict(X_test)

In [34]:
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.923679060665362
[[939  33]
 [ 45   5]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       972
           1       0.13      0.10      0.11        50

    accuracy                           0.92      1022
   macro avg       0.54      0.53      0.54      1022
weighted avg       0.91      0.92      0.92      1022